- name: Testing connectivity
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: ping 127.0.0.1 (loopback inside vagrant)
    wait_for: host=127.0.0.1 timeout=3
  - name: ping 192.168.168.100 (bridge inside vagrant)
    wait_for: host=192.168.168.100 timeout=3
  - name: ssh on 192.168.168.100 (bridge inside vagrant)
    wait_for: host=192.168.168.100 port=22 timeout=3
  - name: nmap eth0 network
    command: nmap -v -o /vagrant/nmap_eth1.log -PE -PA -R -F ${ansible_eth0.ipv4.network}/24
    sudo: true
  - name: nmap eth1 network
    command: nmap -v -o /vagrant/nmap_eth1.log -PE -PA -R -F ${ansible_eth1.ipv4.network}/24 
    sudo: true
  - name: http on google.com
    wait_for: host=google.com port=80 timeout=3